/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForProvidersRouteImport } from './routes/for-providers'
import { Route as ForOrganisationsRouteImport } from './routes/for-organisations'
import { Route as ForFamiliesRouteImport } from './routes/for-families'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTrackingRouteImport } from './routes/app.tracking'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProviderRouteImport } from './routes/app.provider'
import { Route as AppOrganisationRouteImport } from './routes/app.organisation'
import { Route as AppMonitoringRouteImport } from './routes/app.monitoring'
import { Route as AppMarketplaceRouteImport } from './routes/app.marketplace'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppFamilyRouteImport } from './routes/app.family'
import { Route as AppDevicesRouteImport } from './routes/app.devices'
import { Route as AppBookRouteImport } from './routes/app.book'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForProvidersRoute = ForProvidersRouteImport.update({
  id: '/for-providers',
  path: '/for-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForOrganisationsRoute = ForOrganisationsRouteImport.update({
  id: '/for-organisations',
  path: '/for-organisations',
  getParentRoute: () => rootRouteImport,
} as any)
const ForFamiliesRoute = ForFamiliesRouteImport.update({
  id: '/for-families',
  path: '/for-families',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingRoute = AppTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProviderRoute = AppProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganisationRoute = AppOrganisationRouteImport.update({
  id: '/organisation',
  path: '/organisation',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringRoute = AppMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppFamilyRoute = AppFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppBookRoute = AppBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/for-families': typeof ForFamiliesRoute
  '/for-organisations': typeof ForOrganisationsRoute
  '/for-providers': typeof ForProvidersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/book': typeof AppBookRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/family': typeof AppFamilyRoute
  '/app/history': typeof AppHistoryRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/organisation': typeof AppOrganisationRoute
  '/app/provider': typeof AppProviderRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/': typeof AppIndexRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/admin/users': typeof AppAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/for-families': typeof ForFamiliesRoute
  '/for-organisations': typeof ForOrganisationsRoute
  '/for-providers': typeof ForProvidersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/book': typeof AppBookRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/family': typeof AppFamilyRoute
  '/app/history': typeof AppHistoryRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/organisation': typeof AppOrganisationRoute
  '/app/provider': typeof AppProviderRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app': typeof AppIndexRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/admin/users': typeof AppAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/for-families': typeof ForFamiliesRoute
  '/for-organisations': typeof ForOrganisationsRoute
  '/for-providers': typeof ForProvidersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/book': typeof AppBookRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/family': typeof AppFamilyRoute
  '/app/history': typeof AppHistoryRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/organisation': typeof AppOrganisationRoute
  '/app/provider': typeof AppProviderRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/': typeof AppIndexRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/admin/users': typeof AppAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/contact'
    | '/features'
    | '/for-families'
    | '/for-organisations'
    | '/for-providers'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/signup'
    | '/app/alerts'
    | '/app/book'
    | '/app/devices'
    | '/app/family'
    | '/app/history'
    | '/app/marketplace'
    | '/app/monitoring'
    | '/app/organisation'
    | '/app/provider'
    | '/app/settings'
    | '/app/tracking'
    | '/app/'
    | '/app/admin'
    | '/app/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/features'
    | '/for-families'
    | '/for-organisations'
    | '/for-providers'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/signup'
    | '/app/alerts'
    | '/app/book'
    | '/app/devices'
    | '/app/family'
    | '/app/history'
    | '/app/marketplace'
    | '/app/monitoring'
    | '/app/organisation'
    | '/app/provider'
    | '/app/settings'
    | '/app/tracking'
    | '/app'
    | '/app/admin'
    | '/app/admin/users'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/contact'
    | '/features'
    | '/for-families'
    | '/for-organisations'
    | '/for-providers'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/signup'
    | '/app/alerts'
    | '/app/book'
    | '/app/devices'
    | '/app/family'
    | '/app/history'
    | '/app/marketplace'
    | '/app/monitoring'
    | '/app/organisation'
    | '/app/provider'
    | '/app/settings'
    | '/app/tracking'
    | '/app/'
    | '/app/admin'
    | '/app/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ForFamiliesRoute: typeof ForFamiliesRoute
  ForOrganisationsRoute: typeof ForOrganisationsRoute
  ForProvidersRoute: typeof ForProvidersRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-providers': {
      id: '/for-providers'
      path: '/for-providers'
      fullPath: '/for-providers'
      preLoaderRoute: typeof ForProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-organisations': {
      id: '/for-organisations'
      path: '/for-organisations'
      fullPath: '/for-organisations'
      preLoaderRoute: typeof ForOrganisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-families': {
      id: '/for-families'
      path: '/for-families'
      fullPath: '/for-families'
      preLoaderRoute: typeof ForFamiliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tracking': {
      id: '/app/tracking'
      path: '/tracking'
      fullPath: '/app/tracking'
      preLoaderRoute: typeof AppTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider': {
      id: '/app/provider'
      path: '/provider'
      fullPath: '/app/provider'
      preLoaderRoute: typeof AppProviderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organisation': {
      id: '/app/organisation'
      path: '/organisation'
      fullPath: '/app/organisation'
      preLoaderRoute: typeof AppOrganisationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monitoring': {
      id: '/app/monitoring'
      path: '/monitoring'
      fullPath: '/app/monitoring'
      preLoaderRoute: typeof AppMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketplace': {
      id: '/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/family': {
      id: '/app/family'
      path: '/family'
      fullPath: '/app/family'
      preLoaderRoute: typeof AppFamilyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/devices': {
      id: '/app/devices'
      path: '/devices'
      fullPath: '/app/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/book': {
      id: '/app/book'
      path: '/book'
      fullPath: '/app/book'
      preLoaderRoute: typeof AppBookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(AppAdminRouteChildren)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppBookRoute: typeof AppBookRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppFamilyRoute: typeof AppFamilyRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppMonitoringRoute: typeof AppMonitoringRoute
  AppOrganisationRoute: typeof AppOrganisationRoute
  AppProviderRoute: typeof AppProviderRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTrackingRoute: typeof AppTrackingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppBookRoute: AppBookRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppFamilyRoute: AppFamilyRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppMonitoringRoute: AppMonitoringRoute,
  AppOrganisationRoute: AppOrganisationRoute,
  AppProviderRoute: AppProviderRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTrackingRoute: AppTrackingRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ForFamiliesRoute: ForFamiliesRoute,
  ForOrganisationsRoute: ForOrganisationsRoute,
  ForProvidersRoute: ForProvidersRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
